### ISSUE TITLE
cmidi2_convert_midi1_to_ump : what does the bytestream look like?

### ISSUE THREAD

**Issue by jcelerier** [atsushieno/cmidi2#14]
I'm trying to follow this function to understand if the bytestream has all the UMPs padded to 4 uint32_t / 16-bytes or not.

e.g. let's say I want to convert 3 MIDI timecode successive which are 4-byte UMPs: does the resulting bytestream look like (with x being a byte)

```
| x x x x | x x x x | x x x x | 
```
or
```
| x x x x 0 0 0 0 0 0 0 0 0 0 0 0 | x x x x 0 0 0 0 0 0 0 0 0 0 0 0  | x x x x 0 0 0 0 0 0 0 0 0 0 0 0 |
```

?

thanks !

**Comment by jcelerier** [comment]
well, answered my own question by trying, it's the former :)

**Comment by atsushieno** [comment]
I guess you are talking about Delta Clockstamp message (new in June 2023 Updates). Yes, it is one 32-bit packet, with 20-bits `delta_clockstamp` field. The packet format looks like this (sorry for partial Japanese, it's quoted from my book):

![DCTPQ and Delta Clockstamp messages](https://i.imgur.com/n7vWR0V.png)

With the appropriate DCTPQ setup, it should cover the 3 bytes in MIDI 1.0 bytestream.

Let me know if you found any issues regarding these new features. I haven't used them by myself in cmidi2 yet (I did use it a lot using my Kotlin library...)
