### ISSUE TITLE
Const-correctness

### ISSUE THREAD

**Issue by jcelerier** [atsushieno/cmidi2#9]
Hi!
I've been starting to use cmidi2 for the MIDI 2 support in https://github.com/jcelerier/libremidi, it works great!

I have a question: most of the API takes uint32_t* even when no modification is made to the data. would you be open to a patch that adds const everywhere possible so that the user does not have to cast, for instance if reading midi data that gives a const uint32_t* ? 

thanks for this super useful work!

**Comment by atsushieno** [comment]
> I have a question: most of the API takes uint32_t* even when no modification is made to the data. would you be open to a patch that adds const everywhere possible so that the user does not have to cast, for instance if reading midi data that gives a const uint32_t* ?

Oh that would be great, I appreciate that! It was just sloppy code so far.

**Comment by atsushieno** [comment]
fixed by #10
